### ISSUE TITLE
Group by() exercise unrelated to concept being taught

### ISSUE THREAD

**Issue by walwoodr** [learn-co-curriculum/sql-grouping-and-sorting-readme#15]
The exercise under GROUP BY() doesn't even include a group by keyword, and introduces a 3-part join which is a concept that hasn't been introduced yet.

**Comment by aturkewi** [comment]
Thanks for raising this :)
This issue is also showing up on the `v-000` deploy. https://github.com/learn-co-students/sql-grouping-and-sorting-readme-v-000/issues/1#issuecomment-299610694

Tagging @Lukeghenco @genericlady

**Comment by maxwellbenton** [comment]
Hi @walwoodr,

Thank you for opening this issue. We've updated this lesson and made changes based on your feedback. We've updated the `GROUP BY` section of this lesson to display an actual example using `GROUP BY` and included some additional explanation on how the query works, which should resolve this issue.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
