### ISSUE TITLE
Resource link leads to 'High Risk website' in Chrome

### ISSUE THREAD

**Issue by sebge-1** [learn-co-curriculum/sql-grouping-and-sorting-readme#16]
High Risk Website Blocked
Location: http://www.programmerinterview.com/index.php/database-sql/having-vs-where-clause/
Access has been blocked as the threat JS/RefC-Gen has been found on this website.
Return to the page you were previously viewing.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
It appears that this issue may have been fixed on their end.

Thanks for your feedback! 💙
