### ISSUE TITLE
Link from Grouping & Sorting data leads to high risk website

### ISSUE THREAD

**Issue by infopro94** [learn-co-curriculum/sql-grouping-and-sorting-readme#18]
The link to http://www.programmerinterview.com/index.php/database-sql/having-vs-where-clause/ was stopped by Sophos. 

![screen shot 2017-11-04 at 11 49 08 am](https://user-images.githubusercontent.com/25396051/32407423-b07a2d10-c156-11e7-84ee-12882ad07a18.png)

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
It appears that this issue may have been fixed on their end.

Thanks for your feedback! 💙
