### ISSUE TITLE
Group By() Exercise could afford to have a more detailed explanation

### ISSUE THREAD

**Issue by cboujoukos** [learn-co-curriculum/sql-grouping-and-sorting-readme#19]
In the Group By() exercise in this lesson it would be helpful if the explanation went into some detail about _how_ the two JOIN statements refine the results so the resulting SUM is not the sum of all net_worths, but rather just the sum of net_worths of cats that belong to owner 2.
It was a little tough to get a handle on since this is the first time in our lessons we have encountered two JOIN statements in a single query, but that is just glossed over and then not mentioned again in the explanation.

Hope that was helpful!

**Comment by maxwellbenton** [comment]
Hi @cboujoukos,

Thank you for opening this issue. We've updated this lesson and made changes based on your feedback. We've included additional instructions and discussion on the two joins in the `Group By` exercise, which should improve understanding of this query for future students.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
