### ISSUE TITLE
needs group by + aggregators, having, double joins

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/sql-grouping-and-sorting-readme#2]
without the above stuff as code-along example, students will not be able to do the crowdfunding and library labs, which are the main labs of this unit. 

@AnnJohn @jmburges

**Comment by AnnJohn** [comment]
@SophieDeBenedetto is this still an issue or can it be closed? Thanks

**Comment by SophieDeBenedetto** [comment]
can be closed!
