### ISSUE TITLE
"CODE ALONG IV: HAVING VS WHERE CLAUSE" is misleading and doesn't explain the real difference between HAVING and WHERE

### ISSUE THREAD

**Issue by arye-eidelman** [learn-co-curriculum/sql-grouping-and-sorting-readme#20]
### the difference between them is:
HAVING filters out groups of rows, created by 'GROUP BY'
WHERE filters out rows

as a by-product of that:

- HAVING supports aggregate functions as it has to work with groups of rows. so for example, if there are multiple integers in a group it can filter out the groups with a low average, a high total (sum) or count how many rows are in the group.

- WHERE on the other hand deals with each row individually so aggregate functions make no sense for what would you be aggregating?

### it also doesn't mention the difference in syntax.

HAVING is __after__ GROUP BY and WHERE is __before__ GROUP BY changing the order will produce a  syntax error.
```
SELECT 
FROM
JOIN
  ON
WHERE
GROUP BY
HAVING
ORDER BY
LIMIT
```
### [__here__  is a better tutorial](https://www.essentialsql.com/what-is-the-difference-between-where-and-having-clauses/) to use instead of [www.programmerinterview.com...sql/having-vs-where...](http://www.programmerinterview.com/index.php/database-sql/having-vs-where-clause/)

also, see this [stackoverflow answer with close too 250 upvotes explaining this](https://stackoverflow.com/a/9253267/3458162)

--------------
if only I knew this earlier I wouldn't get this error as often
```
SQLite3::SQLException:
     near "WHERE": syntax error
```

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
