### ISSUE TITLE
Different output for SELECT statement in Code Along IV than the exercise shows

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/sql-grouping-and-sorting-readme#22]
There's a bit of a discrepancy in Code Along IV: HAVING vs. WHERE clause.
In the code-along, they show this line of code to execute in SQLite3:

**SELECT** employee, **SUM**(bonus) **from** employee_bonus **group by** employee;

According to the lesson, the following output is returned:

Employee | Bonus

Matthew | 1500
Abigail | 3250
Tom | 700

However, I tried this out in SQLite3. The information is all there, and it IS accurate, but the order that the results are shown in, and the names of the columns, are different:

employee | SUM(bonus)

Abigail | 3250
Matthew | 1500
Tom | 700

This isn't a major issue, but I thought it was worth pointing out just the same. As always, thanks for looking into this!

---Sdcrouse

**Comment by maxwellbenton** [comment]
Hey @Sdcrouse,

This should be fixed now. Thanks for your feedback!

**Comment by Sdcrouse** [comment]
Thanks! I just saw the updated README. The rows are in the right order now, but I don't think the columns are named correctly. Not a big issue though.
