### ISSUE TITLE
Query mistake

### ISSUE THREAD

**Issue by hsztan** [learn-co-curriculum/sql-grouping-and-sorting-readme#23]
`SELECT SUM(cats.net_worth)
FROM owners
INNER JOIN cats_owners
ON owners.id = cats_owners.owner_id
JOIN cats ON cats_owners.cat_id = cats.id
WHERE cats_owners.owner_id = 2;`

It's trying SELECTing cats.net_worth table FROM owners. I believe it should be SELECTing cats.net_worth FROM cats.

`SELECT SUM(cats.net_worth)
FROM owners
INNER JOIN cats_owners
ON owners.id = cats_owners.owner_id
JOIN cats ON cats_owners.cat_id = cats.id
WHERE cats_owners.owner_id = 2;`

**Comment by maxwellbenton** [comment]
Hi @hsztan,

Thank you for opening this issue. We've updated this lesson and made changes based on your feedback. The provided code does select from cats, joining all three tables. However, this lesson did not clearly explain this process, so additional instructions have been added to improve the clarity of the section, which should resolve this confusion for future students.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
