### ISSUE TITLE
incorrect table name in SQL code

### ISSUE THREAD

**Issue by audefaucheux** [learn-co-curriculum/sql-grouping-and-sorting-readme#24]
There is a mistake in the below query. The table "owners" take an 's' at the end. However in the select section, the "s" of the table has been missed out to select the owners.name

SELECT **owner.name**, SUM(cats.net_worth)
FROM owners
INNER JOIN cats_owners
ON owners.id = cats_owners.owner_id
JOIN cats ON cats_owners.cat_id = cats.id
GROUP BY owners.name;

**Comment by sgharms** [comment]
Absolutely right! Fixed!
