### ISSUE TITLE
SQL > Table Relations > Grouping and Sorting Data

### ISSUE THREAD

**Issue by DesterStorm** [learn-co-curriculum/sql-grouping-and-sorting-readme#26]
SELECT owner.name, SUM(cats.net_worth)
FROM owners
INNER JOIN cats_owners
ON owners.id = cats_owners.owner_id
JOIN cats ON cats_owners.cat_id = cats.id
GROUP BY owners.name;

After SELECT, owner.name should be owners.name. By running owner.name, this error is raised:
Error: no such column: owner.name

**Comment by sgharms** [comment]
You're right! Fixed in 60bbe67.
