### ISSUE TITLE
Incorrect Description Based on Data Given

### ISSUE THREAD

**Issue by replacem3nts** [learn-co-curriculum/sql-grouping-and-sorting-readme#27]
Line 247-248 of the README says "while Penny is the owner of Lil' Bub (181600)."

However, as can be seen in the below screenshot, when inserting the data, "Lil' Bub" is not assigned an owner. (cat_owners is line 100 of the README).

<img width="1086" alt="Screen Shot 2020-03-19 at 2 25 44 PM" src="https://user-images.githubusercontent.com/57644669/77101418-a551f980-69ed-11ea-9320-2d0b91af616f.png">

**Comment by sylwiavargas** [comment]
Good catch! Fixed it!
