### ISSUE TITLE
Lil' Bub Net Worth incorrect?

### ISSUE THREAD

**Issue by rosenbergmichael** [learn-co-curriculum/sql-grouping-and-sorting-readme#28]
The original tables show Lil' Bub's net worth to be 2000000 but as the lesson goes on, it references Lil' Bub's net worth to be 181600 (Grumpy Cat's net worth).

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
