### ISSUE TITLE
Discrepancy in cats networth causing errors in code-along

### ISSUE THREAD

**Issue by IgoVeyner** [learn-co-curriculum/sql-grouping-and-sorting-readme#29]
Lil bub's net worth was set to 2000000 originally and later on was referenced as 181600.

That second net worth is actually Grumpy Cat's. 

This discrepancy makes the code-along very difficult to follow as the return values mentioned as "should be" will not occur if you actually follow the readme.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
